//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid BossAI = new Guid("6709d383-0541-49b2-b2e9-f0b113709e8b");
		public static readonly Guid Scan = new Guid("a53541db-ac71-4e21-8a99-75b424bd66cb");

    }
}
